#주제도 설정 엑셀 파일 위치
#excelPath=d:/coops/문서/mapplan.xlsx
#excelPath=D:/coops/app/new_mapplan/mapplan.xlsx
#excelPath=D:/coops/2024/tileset/origin/mapplan.xlsx
excelPath=F:/coops/project/out/emap.xlsm
#excelPath=D:/coops/2024/20240719/mapplan.xlsx
#shape file 최상위 위치
shapePath=F:/coops/바로E맵/02.데이터셋/01.SHP

#emap 최상위 위치
emapPath=F:/tiles

#저장될 위치
#dstPath=f:/coops/2024/tileset/output/emapv
#dstPath=E:/temp/output/emapv
dstPath=F:/coops/2024/tileset/output/emapv

#레이어 파일을 생성할 경우
makeLayer=true

isSimple=false

#주제도 설정 파일을 생성할 경우
makeServiceInfo=true

#주제도 설정 파일에서 반복으로 주기를 표현하는 레이어를 생성할 경우
makeGridLayer=false

#타일을 생성할 경우
makeTile=true

#주제도 엑셀에 정의된 tile sheet의 이름을 “,” 구분자로 설정함.
tileNames=emp01

#타일 생성시 사용할 쓰레드 개수
tileThread=1

#타일 이어쓰기
tileUpdate=false

#타일 mbr 업데이트
tileMbrUpdate=true

#타일 생성 MBR(minx,miny,maxx,maxy)
#서울
#mbr=755237,1396133,1420857,2159490
mbr=1144628.7327105456,1683448.4486146476,1149012.7327105456,1689096.4486146476

#타일 시작 레벨
startLevel=1
#타일 종료 레벨
endLevel=14

# HD Mode  
hdMode=true

#타일 색상수
colorCnt=50

#폰트 경로
fontPath=E:/temp/font
