# 기본 핸들러 설정
#handlers = java.util.logging.ConsoleHandler, java.util.logging.FileHandler
handlers = java.util.logging.FileHandler

# 콘솔 핸들러 설정
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# 파일 핸들러 설정
java.util.logging.FileHandler.level = INFO
java.util.logging.FileHandler.pattern = logs/geotools.log
java.util.logging.FileHandler.limit = 5000000        # 로그 파일 최대 크기 (5MB)
java.util.logging.FileHandler.count = 3             # 순환 로그 파일 갯수
java.util.logging.FileHandler.append = true         # 기존 파일에 추가
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter

# GeoTools 로그 설정
org.geotools.level = INFO