#주제도 설정 엑셀 파일 위치
#excelPath=d:/coops/문서/mapplan.xlsx
#excelPath=D:/coops/app/new_mapplan/mapplan.xlsx
#excelPath=D:/coops/2024/tileset/origin/mapplan.xlsx
excelPath=F:/coops/2024/app/per/per.xlsx
#excelPath=D:/coops/2024/20240719/mapplan.xlsx
#shape file 최상위 위치
shapePath=f:/coops/2024/tileset/origin/shape

#emap 최상위 위치
emapPath=E:/app/jetty-distribution-9.4.35.v20201120/webapps/root

#저장될 위치
dstPath=f:/coops/2024/tileset/output/per

#레이어 파일을 생성할 경우, 데이터 변경
makeLayer=false

isSimple=false

#주제도 설정 파일을 생성할 경우 ==> 스타일 변경, 디자인 변경
makeServiceInfo=true

#주제도 설정 파일에서 반복으로 주기를 표현하는 레이어를 생성할 경우, 격자 변경
makeGridLayer=false

#타일을 생성할 경우
makeTile=true

#주제도 엑셀에 정의된 tile sheet의 이름을 “,” 구분자로 설정함.
#tileNames=per01,per02,per03,per04,per05
tileNames=per01


#타일 생성시 사용할 쓰레드 개수
tileThread=18

#타일 이어쓰기 - 전국 자료 생성할때에 true로 해야함. / 이게 true이면 tileMbrUpdate는 무조건 false
tileUpdate=false

#타일 mbr 업데이트(mbr영역만 업데이트할때에는 tileUpdate는 false로 증분 업데이트를 꺼야함)
tileMbrUpdate=true

#타일 생성 MBR(minx,miny,maxx,maxy)
#서울
#mbr=755237,1396133,1420857,2159490
#아산 = 936730.18784,1848179.8172799996,970010.18784,1885299.8172799996
#mbr=936730.18784,1848179.8172799996,970010.18784,1885299.8172799996
#mbr=477508,2848541,479525,2849832
#mbr=1116302.179409304,1665121.762869185,1165838.179409304,1714017.762869185
mbr=1144628.7327105456,1683448.4486146476,1149012.7327105456,1689096.4486146476
#타일 시작 레벨
startLevel=1
#타일 종료 레벨
endLevel=14

# HD Mode  
hdMode=true

#타일 색상수
colorCnt=50