#주제도 설정 엑셀 파일 위치
#excelPath=d:/coops/문서/mapplan.xlsx
#excelPath=D:/coops/app/new_mapplan/mapplan.xlsx
#excelPath=D:/coops/2024/tileset/origin/mapplan.xlsx
excelPath=f:/coops/2024/tileset/origin/reg10_temp.xlsx
#excelPath=D:/coops/2024/20240719/mapplan.xlsx
#shape file 최상위 위치
shapePath=f:/coops/2024/tileset/origin/shape1

#emap 최상위 위치
emapPath=E:/app/jetty-distribution-9.4.35.v20201120/webapps/root

#저장될 위치
dstPath=f:/coops/2024/tileset/output/reg10_temp

#레이어 파일을 생성할 경우
makeLayer=true

isSimple=false

#주제도 설정 파일을 생성할 경우
makeServiceInfo=true

#주제도 설정 파일에서 반복으로 주기를 표현하는 레이어를 생성할 경우
makeGridLayer=false

#타일을 생성할 경우
makeTile=false

#주제도 엑셀에 정의된 tile sheet의 이름을 “,” 구분자로 설정함.
tileNames=reg11

#타일 생성시 사용할 쓰레드 개수
tileThread=10

#타일 이어쓰기
tileUpdate=false

#타일 mbr 업데이트
tileMbrUpdate=false

#타일 생성 MBR(minx,miny,maxx,maxy)
#서울
mbr=755237,1396133,1420857,2159490


#타일 시작 레벨
startLevel=1
#타일 종료 레벨
endLevel=14

