#now=d:/coops/service
now=f:/coops/tileset/output|f:/coops/tileset/output1
#previous=d:/coops/previous&d:/coops/previous1
dll=d:/coops/jetty-distribution-9.4.18.v20190429/map_service/lib


isAuthority=false

local=192.168.60.210:8070
uri=/ver1/authority
servers=192.168.60.210:6070|192.168.60.210:8070
serverGroup=0

#dbUrl=jdbc:postgresql://119.196.18.2:5555/test
#dbUrl=jdbc:postgresql://119.196.18.2:5555/tes
dbUrl=jdbc:postgresql://119.196.18.2:15432/test
dbUser=test
dbPassword=test1234

isSaveServer=false
saveServer=192.168.60.210:7070
saveServerThreadCnt=10
saveResultUrl=http://192.168.100.209:8070/ver1/authority

savePath=F:/coops/2024/tileset/save

convPath=F:/coops/2024/tileset/conv

logPath=D:/workspace/MapService/logs


#logPath=D:/coops/jetty-distribution-9.4.35.v20201120/logs

#isSearchLog=true
#isSearchUserLog=true
#isAnalysisLog=true
#isReqLog=true
#isLoadLog=true
#loadLogInterval=5

#emap \uCD5C\uC0C1\uC704 \uC704\uCE58
#emapPath=E:/app/jetty-distribution-9.4.35.v20201120/webapps/root
emapPath=F:/tiles

rasterPath=F:/coops/2024/tileset/origin/raster
errorImage=D:/workspace/MapService/map_service/error.png


# HD Mode  
hdMode=true

#폰트 경로
fontPath=E:/temp/font