#now=d:/coops/service
now=f:/coops/2024/tileset/output
previous=d:/coops/previous&d:/coops/previous1
dll=d:/coops/jetty-distribution-9.4.18.v20190429/map_service/lib
logPath=D:/coops/jetty-distribution-9.4.35.v20201120/logs
isSearchLog=true
isSearchUserLog=true
isAnalysisLog=true
isReqLog=true
isLoadLog=true
loadLogInterval=5

#emap \uCD5C\uC0C1\uC704 \uC704\uCE58
#emapPath=E:/app/jetty-distribution-9.4.35.v20201120/webapps/root